services:
  postgres:
    image: postgres:16
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: faang
      POSTGRES_PASSWORD: faang
      POSTGRES_DB: faang
    ports:
      - "5432:5432"
